name: Dockerize automation
on: push

# always do the Build step first with: (1) runs-on (2)container and add if it (3)needs a previous job
# then it is time for the steps: (1) Checkout repository (2) Build or get the already build artifact (3) Do the job
#

env:
  github_username: mihaelagavrilova04
  github_password: ${{ secrets.GITHUB_TOKEN }} # автоматично генериран, не си го добавям ръчно в secrets
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build application
        run: ci/build-app.sh

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build
          path: app/build/libs/*.jar

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Build
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get the already built artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-build
          path: ./app/

      - name: Apply tests
        run: ci/unit-test-app.sh

  Docker:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      packages: write  # за да може да пушва към GitHub registry

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-build
          path: build/libs/

      - name: Build docker image using script
        run: bash ci/build-docker.sh

      - name: Push docker image
        run: bash ci/push-docker.sh


